---

- name: Create database
  mysql_db:
    name=cinder
    encoding=UTF8
    login_user=root
    login_password={{ mysql_root_password }}
    state=present

- name: Assign privileges to cinder user
  mysql_user: 
    name=cinder
    password={{ CINDER_DBPASS }}
    priv=cinder.*:ALL,GRANT
    state=present
    host={{item}}
  with_items:
    - localhost
    - '%'
