---

- name: Create database
  mysql_db:
    name=nova
    encoding=UTF8
    login_user=root
    login_password={{ mysql_root_password }}
    state=present

- name: Assign privileges to nova user
  mysql_user: 
    name=nova
    password={{ NOVA_DBPASS }}
    priv=nova.*:ALL,GRANT
    state=present
    host={{item}}
  with_items:
    - localhost
    - '%'
