---

- name: Install packages
  yum: name={{item}}
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - openstack-nova-compute
    - libvirt-python

- name: Install client
  yum: name='python-novaclient'

- name: Check if hardware virtualization available
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: hw_virt
  failed_when: False
  changed_when: False

- name: Apply config if hardware virtualization isn't supported
  command: "~/openstack-config-helper.sh /etc/nova/nova.conf libvirt virt_type qemu"
  when: hw_virt|failed
  register: res
  changed_when: res.stdout == '1'

- name: Install packages for modifying SELinux
  yum:
    name='libsemanage-python'
    state=present

- seboolean:
    name=virt_use_execmem
    state=yes
    persistent=yes
  when: hw_virt|failed

- name: Setup configuration files
  command: "~/openstack-config-helper.sh {{item.0.path}} {{item.1}}"
  register: res
  changed_when: res.stdout == '1'
  with_subelements:
    - nova_config
    - values

- name: Initialize database
  nova_manage: action=dbsync

- name: Start and enable services
  service:
    name={{item}}
    state=started
    enabled=yes
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-consoleauth
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy
    - libvirtd
    - dbus
    - openstack-nova-compute
