---

- name: Create database
  mysql_db:
    name=keystone
    encoding=UTF8
    login_user=root
    login_password={{ mysql_root_password }}
    state=present

- name: Assign privileges to keystone user
  mysql_user:
    name=keystone
    password={{ KEYSTONE_DBPASS }}
    priv=keystone.*:ALL,GRANT
    state=present
    host={{item}}
  with_items:
    - localhost
    - '%'
