---

- name: Install packages
  yum: name={{item}}
  with_items:
    - openstack-keystone

- name: Install client
  yum: name='python-keystoneclient'

- name: Setup configuration files
  command: "~/openstack-config-helper.sh {{item.0.path}} {{item.1}}"
  register: res
  changed_when: res.stdout == '1'
  with_subelements:
    - keystone_config
    - values

- name: Check database version
  shell: v=$(su -s /bin/sh -c "keystone-manage db_version" keystone) && [[ $v != 0 ]]
  register: dbReady
  changed_when: False
  failed_when: False

- name: Execute keystone-manage sync
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  when: dbReady|failed

- command: >
    keystone-manage pki_setup
    --keystone-user keystone
    --keystone-group keystone

- file:
    name=/etc/keystone/ssl
    owner=keystone
    group=keystone
    mode=770
    recurse=yes

- name: Start and enable keystone service
  service:
    name='openstack-keystone'
    state=started
    enabled=yes

# - shell: >
#     (crontab -l -u keystone 2>&1 | grep -q token_flush) ||
#       echo '@hourly /usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1' >> /var/spool/cron/keystone
