---

- name: Create database
  mysql_db:
    name=neutron
    encoding=UTF8
    login_user=root
    login_password={{ mysql_root_password }}
    state=present

- name: Assign privileges to neutron user
  mysql_user:
    name=neutron
    password={{ NEUTRON_DBPASS }}
    priv=neutron.*:ALL,GRANT
    state=present
    host={{item}}
  with_items:
    - localhost
    - '%'
