---

- name: Install packages
  yum: name={{item}}
  with_items:
    - openstack-glance

- name: Install client
  yum: name='python-glanceclient'

- name: Setup configuration files
  command: "~/openstack-config-helper.sh {{item.0.path}} {{item.1}}"
  register: res
  changed_when: res.stdout == '1'
  with_subelements:
    - glance_config
    - values

- name: Check database version
  shell: v=$(su -s /bin/sh -c "glance-manage db_version" glance) && [[ $v != 0 ]]
  register: dbReady
  changed_when: False
  failed_when: False

- name: Execute glance-manage sync
  command: su -s /bin/sh -c "glance-manage db_sync" glance
  when: dbReady|failed

- name: Start and enable services
  service:
    name={{item}}
    state=started
    enabled=yes
  with_items:
    - openstack-glance-api
    - openstack-glance-registry
